### ISSUE TITLE
Cannot get Service Tokens to work

### ISSUE THREAD

**Issue by kadaan** [BojanZelic/cloudflare-zero-trust-operator#131]
I'm able to get Service Tokens to be created, but when I try to reference them in an Access Group I just get this error: `unable to create access group: unable to create access groups: error from makeRequest: access.api.error.invalid_request: include field should not be empty (12130)`.

My service tokens are created before the access group by leveraging Flux Kustomizations.

Service Token Resource:
```
---
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareServiceToken
metadata:
  name: myService
  namespace: myNamespace
spec:
  name: myService
```

Access Group Resource:
```
---
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessGroup
metadata:
  name: myService
  namespace: myNamespace
spec:
  name: MyService
  include:
    - serviceToken:
        - valueFrom:
            name: myService
            namespace: myNamespace
  require:
    - country:
      - US
```

This structure is similar to OIDC Claims.  What am I doing wrong, or is this a bug?

**Comment by Drey563** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by kadaan** [comment]
Figured it out, but it was kind of a pain.  `CloudflareAccessGroup` can reference service tokens, but from what I can tell there is no resolution of `valueFrom`.  That only happens for `CloudflareAccessApplication`.  Rather then write it like above, in the current state it should be written like: 

Service Token Resource:

```
---
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareServiceToken
metadata:
  name: myService
  namespace: myNamespace
spec:
  name: myService
```

Cloudflare Application Resource:

```
---
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: myApplication
  namespace: myNamespace
spec:
  ...
  policies:
    - name: myService
      decision: non_identity
      include:
        - serviceToken:
            - valueFrom:
                name: myService
                namespace: myNamespace
```

@BojanZelic It would be good if CloudflareAccessGroup controller also resolved these references.
