### ISSUE TITLE
Update documentation - Clearer usage regarding namespaces

### ISSUE THREAD

**Issue by Amphaal** [BojanZelic/cloudflare-zero-trust-operator#149]
Make available examples use namespaces: 
- Should all `CloudflareAccessApplication` and `CloudflareAccessGroup` be in `zero-trust-system` ? 
- Can they live along their related `Pod` / `Deployment` / `Service` / `Ingress`, using the same namespace (eg., `prometheus`, `dashboard`, `ldap-admin`...) ?

**Comment by BojanZelic** [comment]
Updated the example to include `namespace: default` 

you can install the resources in any namespace

**Comment by Amphaal** [comment]
Correct me if I am wrong, but `CloudflareAccessGroup` IDs specified in any `CloudflareAccessApplication` **would not** be found if declared outside of `CloudflareAccessApplication` namespace scope.

**Comment by BojanZelic** [comment]
You should be able to access cross-namespace resources; 

```
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessGroup
metadata:
  name: accessgroup-example
  namespace: namespace1
spec:
  name: my access group
  include:
    - emails:
      - testemail1@domain.com
      - testemail2@domain.com
```

```
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: domain-example
  namespace: namespace2
spec:
  name: my application
  domain: domain.example.com
  autoRedirectToIdentity: true
  policies: 
    - name: Allow testemail1
      decision: allow
      include:
        - emails:
          - testemail3@domain.com
        - accessGroups:
            - valueFrom:
                name: accessgroup-example
                namespace: namespace1
```
