### ISSUE TITLE
`Error: couldn't find key CLOUDFLARE_API_KEY in Secret zero-trust-system/cloudflare-creds` while using `CLOUDFLARE_API_TOKEN`

### ISSUE THREAD

**Issue by Amphaal** [BojanZelic/cloudflare-zero-trust-operator#150]
Here is my ansible template that generate the Secret manifest: 

```
apiVersion: v1
metadata:
  name: cloudflare-creds
  namespace: zero-trust-system
kind: Secret
type: Opaque
stringData:
  CLOUDFLARE_ACCOUNT_ID: "{{ iac__cloudflare__account_id }}"
  # Either EMAIL+KEY or TOKEN must be supplied
  # CLOUDFLARE_API_EMAIL: whatever
  # CLOUDFLARE_API_KEY: whatever
  CLOUDFLARE_API_TOKEN: "{{ iac__cloudflare__api_token }}"
```

both `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` are filled with data, and yet I get the error while the Deployment try to initiate the `Pod`.
