### ISSUE TITLE
Include documentation regarding `WARP` / `App Launcher` special applications

### ISSUE THREAD

**Issue by Amphaal** [BojanZelic/cloudflare-zero-trust-operator#153]
Since the Cloudflare API is not very clear on how to automatize configuration of said pre-existing `WARP` and `App Launcher` applications, maybe we should provide samples on how to use it ? Maybe should we have it embedded and configurable through helm ? 

Here's what I do:

```
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: warp
  namespace: "{{ cf_zto__namespace }}"
  annotations:
    cloudflare.zelic.io/prevent-destroy: "true" # SHOULD NOT DELETE
spec:
  name: Warp Login App # SPECIFIC & REQUIRED
  domain: "{{ iac__cloudflare__zero_trust__team_name }}.cloudflareaccess.com/warp" # SPECIFIC & REQUIRED
  type: warp # SPECIFIC & REQUIRED
  sessionDuration: 24h
  autoRedirectToIdentity: false # REQUIRED to be false
  policies: 
    - name: "{{ cf_zto__ldap_policy__name }}"
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
              name: "{{ cf_zto__ldap_policy__access_group_id }}"
              namespace: "{{ cf_zto__namespace }}"
---
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: app-launcher
  namespace: "{{ cf_zto__namespace }}"
  annotations:
    cloudflare.zelic.io/prevent-destroy: "true"  # SHOULD NOT DELETE
spec:
  name: App Launcher # SPECIFIC & REQUIRED
  domain: "{{ iac__cloudflare__zero_trust__team_name }}.cloudflareaccess.com" # SPECIFIC & REQUIRED
  type: app_launcher # SPECIFIC & REQUIRED
  sessionDuration: 24h
  autoRedirectToIdentity: false # REQUIRED to be false
  policies: 
    - name: "{{ cf_zto__ldap_policy__name }}"
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
              name: "{{ cf_zto__ldap_policy__access_group_id }}"
              namespace: "{{ cf_zto__namespace }}"
```
